#!/usr/bin/env bash
#
# Release the campbooks CLI from a `cli/vX.Y.Z` tag:
#   1. cross-compile the static binary for darwin/linux × amd64/arm64,
#   2. publish a GitHub release on the (prefixed) tag with the archives,
#   3. regenerate the Homebrew formula and push it to notacamp/homebrew-tap.
#
# Why this script instead of GoReleaser: the CLI is a nested Go module released
# on a `cli/`-prefixed tag line (so it doesn't collide with the app's `vX.Y.Z`
# image releases). GoReleaser couples the version to the release tag and only
# handles a tag prefix via its Pro-only `monorepo` feature, so on the OSS build
# it can't separate the version (0.1.0) from the release tag (cli/v0.1.0). Doing
# it by hand keeps the two independent and needs no license.
#
# Env: GH_TOKEN (release), HOMEBREW_TAP_TOKEN (push to the tap), GITHUB_REF_NAME.
set -euo pipefail

TAG="${GITHUB_REF_NAME:?GITHUB_REF_NAME is required (the cli/vX.Y.Z tag)}"
VERSION="${TAG#cli/v}"                 # cli/v0.1.0 -> 0.1.0
REPO="notacamp/campbooks"
TAP="notacamp/homebrew-tap"
BASE_URL="https://github.com/${REPO}/releases/download/${TAG}"
PLATFORMS="darwin/amd64 darwin/arm64 linux/amd64 linux/arm64"

echo "Releasing campbooks CLI ${VERSION} (tag ${TAG})"

rm -rf dist && mkdir -p dist
for platform in $PLATFORMS; do
  os="${platform%/*}"; arch="${platform#*/}"
  name="campbooks_${VERSION}_${os}_${arch}"
  echo "  building ${name}"
  ( cd cli && GOOS="$os" GOARCH="$arch" CGO_ENABLED=0 \
      go build -trimpath -ldflags "-s -w -X main.version=${VERSION}" -o "../dist/${name}/campbooks" . )
  tar -czf "dist/${name}.tar.gz" -C "dist/${name}" campbooks
  rm -rf "dist/${name}"
done
( cd dist && sha256sum ./*.tar.gz > checksums.txt )

# GitHub release on the prefixed tag (idempotent so re-runs/re-tags are safe).
if gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1; then
  echo "  release ${TAG} exists — uploading assets (clobber)"
  gh release upload "$TAG" dist/*.tar.gz dist/checksums.txt --repo "$REPO" --clobber
else
  gh release create "$TAG" dist/*.tar.gz dist/checksums.txt \
    --repo "$REPO" --title "campbooks CLI ${VERSION}" \
    --notes "Developer CLI ${VERSION}. Install with \`brew install notacamp/tap/campbooks\` or \`go install github.com/notacamp/campbooks/cli@latest\`."
fi

# Per-artifact checksums for the formula.
sha() { awk -v f="./$1" '$2 == f { print $1 }' dist/checksums.txt; }
darwin_amd64="$(sha "campbooks_${VERSION}_darwin_amd64.tar.gz")"
darwin_arm64="$(sha "campbooks_${VERSION}_darwin_arm64.tar.gz")"
linux_amd64="$(sha "campbooks_${VERSION}_linux_amd64.tar.gz")"
linux_arm64="$(sha "campbooks_${VERSION}_linux_arm64.tar.gz")"

cat > campbooks.rb <<RUBY
# typed: false
# frozen_string_literal: true

# Generated by cli/scripts/release.sh on each cli/vX.Y.Z release — do not edit.
class Campbooks < Formula
  desc "Developer CLI for Campbooks — drive your inbox, documents, and Scout from the terminal"
  homepage "https://github.com/notacamp/campbooks"
  version "${VERSION}"

  on_macos do
    on_arm do
      url "${BASE_URL}/campbooks_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64}"
    end
    on_intel do
      url "${BASE_URL}/campbooks_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE_URL}/campbooks_${VERSION}_linux_arm64.tar.gz"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "${BASE_URL}/campbooks_${VERSION}_linux_amd64.tar.gz"
      sha256 "${linux_amd64}"
    end
  end

  def install
    bin.install "campbooks"
  end

  test do
    system "#{bin}/campbooks", "--version"
  end
end
RUBY

# Push the formula to the tap.
work="$(mktemp -d)"
git clone --depth 1 "https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/${TAP}.git" "$work"
mkdir -p "$work/Formula"
cp campbooks.rb "$work/Formula/campbooks.rb"
git -C "$work" config user.name "github-actions[bot]"
git -C "$work" config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git -C "$work" add Formula/campbooks.rb
if git -C "$work" diff --cached --quiet; then
  echo "  formula unchanged — nothing to push"
else
  git -C "$work" commit -m "campbooks ${VERSION}"
  git -C "$work" push
  echo "  pushed Formula/campbooks.rb to ${TAP}"
fi
echo "Done."
